config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :devices
      resources :sessions, only: :index do
        collection do
          post :upload_image
        end
      end
    end
  end

  resources :devices
  resources :sessions
  resources :image_stores
  root to: 'devices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  # association
  has_many :sessions, dependent: :destroy

  # validations
  validates :mac_id,
    presence: true,
    uniqueness: true
end

app/models/image_store.rb
class ImageStore < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :image, presence: true
  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png image/svg image/gif)
  belongs_to :session
end

app/models/session.rb
class Session < ApplicationRecord
  has_many :image_stores, dependent: :destroy
  belongs_to :device
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    # Generic API stuff here in this class
    # TODO : Need to have a basic authentication to verify that
    # request cming from our app
    class ApiController < ApplicationController
      protect_from_forgery with: :null_session

      def params_missing?(params_array, keys_array)
        @error_hash = {}
        keys_array.each do |key|
          unless params_array[key].present?
            @error_hash[:message] = (@error_hash.has_key?(:message)) ? @error_hash[:message] + " #{key.to_s} parameter is missing." : "#{key.to_s} parameter is missing."
          end
        end

        @error_hash.merge!(error: "Bad Request") if @error_hash.has_key?(:message)
        @error_hash.has_key?(:message)
      end
    end
  end
end

app/controllers/api/v1/devices_controller.rb
module Api
  module V1
    # Devices Controller
    class DevicesController < ApiController
      before_action :validate_device_params

      def create
        device = create_or_update_device(params[:device])
        session = create_or_update_session(device, params[:device])
        render json: { data: { mac_id: device.mac_id, session_id: session.id }, status: 200 }
      end

      private

        def create_or_update_session(device, params)
          if params[:session_id].present? && params[:training_status] == 'end'
            session = Session.find(params[:session_id])
            session.end_time = DateTime.now
            session.save
          else
            session = Session.create(device_id: device.id, start_time: DateTime.now)
          end
          session
        end

        def create_or_update_device(params)
          mac_id = params[:mac_id]
          device = Device.find_or_create_by(mac_id: mac_id)
          device.name = params[:name] if params[:name].present?
          device.ip = params[:ip] if params[:ip].present?
          device.save
          device
        end

        def validate_device_params
          if params_missing?(device_params, [:mac_id, :training_status])
            # missing parameter
            return render json: @error_hash, status: 400
          end

          if device_params[:session_id].nil? && device_params[:training_status] == 'end'
            return render json: { error: 'Session Id should be present', status: 400 }
          end

          unless ['start', 'end'].include?(device_params[:training_status])
            render json: { error: 'Training status should be start or end', status: 400 }
          end
        end

        def device_params
          params.require(:device).permit(:name, :mac_id, :ip, :training_status, :session_id)
        end
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
module Api
  module V1
    # Sessions Controller
    class SessionsController < ApiController
      before_action :validate_session_params

      def upload_image
        session = Session.find params[:session][:session_id]
        image_store = ImageStore.create(session_id: session.id, image: params[:session][:image])
        render json: { message: 'Successfully uploded imagge', status: 200 }
      end

      private

        def validate_session_params
          if params_missing?(params[:session], [:session_id, :image])
            # missing parameter
            render json: @error_hash, status: 400
          end
        end

        def session_params
          params.require(:session).permit(:session_id, :image, :time)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
# Devices Controller
class DevicesController < ApplicationController
  def index
    @devices = Device.all
  end
end

app/controllers/image_stores_controller.rb
# Image Stores Controller
class ImageStoresController < ApplicationController
  def index
    if params[:session_id].present?
      session = Session.find(params[:session_id])
      @image_stores = session.image_stores
    else
      @image_stores = ImageStore.all
    end
  end
end

app/controllers/sessions_controller.rb
# Sessions Controller
class SessionsController < ApplicationController
  def index
    if params[:device_id].present?
      device = Device.find(params[:device_id])
      @sessions = device.sessions
    else
      @sessions = Session.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_date_time(date)
    return '' if date.nil?

  end
end

app/views/devices/_table.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Mac Id</th>
      <th>Ip</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.id %></td>
        <td><%= device.try(:name) %></td>
        <td><%= device.mac_id %></td>
        <td><%= device.try(:ip) %></td>
        <td>
          <%= link_to 'Sessions', sessions_path(device_id: device.id), title: 'Show Sessions' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/devices/index.html.erb
<section class="page-title">
  <h1>Devices</h1>
</section>
<%= render 'table' %>

app/views/image_stores/_table.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Id</th>
      <th>Device Mac ID</th>
      <th>Image</th>
    </tr>
  </thead>
  <tbody>
    <% @image_stores.each do |image_store| %>
      <tr>
        <td><%= image_store.id %></td>
        <td><%= image_store.session.device.mac_id %></td>
        <td><%= image_tag image_store.image.url(:medium) %>
        <td>
          "Actions"
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/image_stores/index.html.erb
<section class="page-title">
  <h1>ImageStored</h1>
</section>
<%= render 'table' %>

app/views/layouts/_footer.html.erb
<div class='footer pull-right'>
  Neotracker application footer copyright...
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <div  class="navbar-brand">
          <a id="menu-toggle" href="#" class="glyphicon glyphicon-align-justify btn-menu toggle">
              <i class="fa fa-bars"></i>
          </a>
        <a href="#">NeoTracker</a>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
 <div id="sidebar-wrapper">
  <nav id="spy">
    <ul class="sidebar-nav nav">
      <li class="sidebar-brand">
        <a href="#home"><span class="fa fa-home solo">Home</span></a>
      </li>
      <li>
        <%= link_to 'Devices', devices_path %>
      </li>
      <li>
        <%= link_to 'Sessions', sessions_path %>
      </li>
       <li>
        <%= link_to 'Images', image_stores_path %>
      </li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlobImageStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body class=<%= controller_name%>>
    <div id='wrapper' class=<%="#{params[:controller]} #{params[:action]}"%>>
      <!-- sidebar -->
      <%= render 'layouts/sidebar' %>

      <!-- a wrapper element  -->
      <div id='page-wrapper' role='main' class=<%= (@extra_class.present?) ? 'main gray-bg #{@extra_class}' : 'main gray-bg'%>>
        <div class='header'>
          <%= render 'layouts/header'%>
        </div>
        <%= yield%>
        <div class='footer'>
          <%= render 'layouts/footer' %>
        </div>
    </div>
  </body>
</html>